apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: samba-operator
  template:
    metadata:
      labels:
        name: samba-operator
    spec:
      serviceAccountName: samba-operator
      containers:
        - name: samba-operator
          # Replace this with the built image name
          image: quay.io/obnox/samba-operator:v0.0.1
          command:
          - samba-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "samba-operator"
